### ISSUE TITLE
Feature Request: Azure Resource Graph resource

### ISSUE THREAD

**Issue by stuartpreston** [inspec/inspec-azure#182]
Providing an **Azure Resource Graph** (see https://docs.microsoft.com/en-us/azure/governance/resource-graph/overview) resource would allow access to properties returned by Azure resource providers (RPs) without needing to make individual calls to each resource provider. Providing access to the resource graph via a resource would be a logical next step to the deprecated `azure_generic_resource` resource and would provide a future path to auto-generated resources (such as those generated from the [Azure REST API specs](https://github.com/Azure/azure-rest-api-specs)).

## Possible Implementation
TBD

**Comment by omerdemirok** [comment]
@stuartpreston, please [here](https://github.com/inspec/inspec-azure#resource-documentation) for the available azure generic resources, including `azure_graph_generic_resource `, since version `v1.20.0`. 

I hope this resolves this issue.
Please feel free to reopen if you encounter any problems running them.
