### ISSUE TITLE
Add support for the recently added 'AzureCliTokenProvider' authentication option

### ISSUE THREAD

**Issue by JamesDawson** [inspec/inspec-azure#189]
This recently merged [PR](https://github.com/Azure/azure-sdk-for-ruby/pull/2398) into the Azure SDK for Ruby adds support for using the azure-cli to generate access tokens (i.e. via an existing logged-in azure-cli session) - is it feasible for Inspec to utilise this new feature?

## Detailed Description
Extending the authentication options (and presumably profile configuration model?) to support using the above mentioned [`AzureCliTokenProvider`](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/credentials/azure_cli_token_provider.rb).

## Context
Having this option available when running Inspec would greatly enhance & simplify the local dev/test workflow, as users would not have to create SPNs and store those sensitive settings - they could simply run `az login` before running their tests.

## Possible Implementation
If someone could give me a pointer as to where such changes would need to be made, then I'd be willing to attempt an initial PR.

**Comment by JamesDawson** [comment]
After some further reading, I think this is actually more relevant to [Train](https://github.com/inspec/train) - is that right?

**Comment by omerdemirok** [comment]
@JamesDawson, thanks for opening this issue. 
Here are my thoughts:
- Since Inspec is an application, it needs a service principal to talk to Azure.
- `az login` actually stores the sensitive authorization tokens in `.azure/accessTokens.json` possibly in the `home` directory. On the other hand, the Inspec Azure resource pack does not store them and creates new tokens for every test run separately, [here](https://github.com/inspec/inspec-azure/blob/master/libraries/backend/azure_connection.rb#L119).

CC: @skpaterson, @rmoles, @Schwad, @james-stocks.

**Comment by omerdemirok** [comment]
@JamesDawson, please feel free to re-open this issue if you think we should further discuss it.

**Comment by jnikles1** [comment]
Hi, curious if this issue can be re-opened, as this requirement has recently come up for my team at SAP. Could there be some more investigation as to whether this is possible?
