### ISSUE TITLE
Update AzurermAdUsers Documentation

### ISSUE THREAD

**Issue by rmoles** [inspec/inspec-azure#229]
The documentation should be updated for the AzurermAdUsers resource with an example of using the user's filter, added here: #227

**Comment by omerdemirok** [comment]
@rmoles, this feature is provided with the `filter_free_text` parameter of the fully backward compatible  `azure_graph_users` rerource.
Please see [here](https://github.com/inspec/inspec-azure/blob/master/docs/resources/azure_graph_users.md) for some examples.

What they do is filtering the users on the server (Azure).

Instead of this:
```
describe azurerm_ad_users(filter: "userType eq 'Guest'") do
    its('display_names') { should eq [] }
    its('count') {should eq 0}
  end
```
This should be used:
```
describe azure_graph_users(filter_free_text: "userType eq 'Guest'") do
    its('display_names') { should eq [] }
    its('count') {should eq 0}
  end
```

**Comment by rmoles** [comment]
Thanks @omerdemirok
