### ISSUE TITLE
A configurable way to switch between different Azure environments

### ISSUE THREAD

**Issue by qiantaogt** [inspec/inspec-azure#245]
## Detailed Description

Azure has several sovereign regions(such as Azure US Gov, Azure China) whose AD/API access endpoints are different. However currently when executing Azure InSpec profile, it just connects to the default Azure cloud, and there's no setting available to switch to other endpoints.
So I wish inspec-azure can have official support for multiple Azure environments configuration.

## Context

I was trying to use InSpec against Azure China but it didn't work. Since I didn't find any solution in docs, I went to grep the inspec installation directory and found actually those sovereign region environments have been predefined within `embedded\lib\ruby\gems\2.6.0\gems\ms_rest_azure-0.11.2\lib\ms_rest_azure\azure_environment.rb`, but they are never used anywhere.

inspec --version
4.18.114

## Possible Implementation

Now I can workaround it by changing certain ruby files to use AzureChinaCLoud directly, but it's not a complete solution and fallible.
Hope this environments switch can be achieved simply by a flag.
a command option, 
a setting in inspec.yml, 
a param in azure:// target URI
...

**Comment by qiantaosap** [comment]
Hi, I have a try with latest Azure resource pack. The 'endpoint' setting does help switch the connection to other Azure site, but the REST call failures due to bad URL. seems an ending slash is missed here. [azure_environment.rb](https://github.com/inspec/inspec-azure/blob/5723892ffd27ea8b4fb3534c648339fb4c70f34d/libraries/backend/azure_environment.rb#L109)
Also for "**azurerm_**" resources, README says they don't support 'endpoint' setting and will be deprecated in inspec-azure version 2. May I know when the new version will be available? Thanks

**Comment by qiantaosap** [comment]
[issue #289 ](https://github.com/inspec/inspec-azure/issues/289) is opened to track this URL issue.
